version: '3.1'

services:

    mysql:
      image: mysql
      cap_add:
        - SYS_NICE  # CAP_SYS_NICE
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_PASSWORD: password
        MYSQL_DATABASE: database_development
        MYSQL_USER: root
      volumes: 
        - mysql-data:/var/lib/mysql
      networks: 
        - song-network

    api-server:
      depends_on:
        - mysql
      build:
        context: .
        dockerfile: Dockerfile
      image: songapptest
      ports: 
          - "8080:8080"
      networks: 
        - song-network

    # migrateAndSeed:
    #     image: songappcomplete
    #     command: ["./wait-for-it/wait-for-it.sh", "mysql:3306", "--", "npm", "run", "dbup"]
    #     links:
    #       - mysql
    #     depends_on:
    #       - mysql
    #     networks: 
    #       - song-network

    # react-app:
    #     depends_on:
    #         - api-server
    #     image: songappclient
    #     ports: 
    #         - "3000:3000"
    #     stdin_open: true
        # networks: 
        #   - song-network

networks:
  song-network:
    driver: bridge
volumes: 
  mysql-data:
    driver: local
