version: '3.1'

services:

    mysql:
      image: mysql
      cap_add:
        - SYS_NICE  # CAP_SYS_NICE
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_PASSWORD: password
        MYSQL_DATABASE: database_development
        MYSQL_USER: root
      networks: 
        - mern-app
      volumes: 
        - mysql-data:/var/lib/mysql

    api-server:
        depends_on:
            - mysql
        image: songappserver
        ports: 
            - "5000:5000"
        networks:
          - mern-app
            
    react-app:
        depends_on:
            - api-server
        image: songappclient
        ports: 
            - "3000:3000"
        stdin_open: true
        networks: 
          - mern-app

    migrateAndSeed:
        image: songappserver
        command: ["./wait-for-it/wait-for-it.sh", "mysql:3306", "--", "npm", "run", "dbup"]
        links:
          - mysql
        depends_on:
          - mysql
        networks: 
          - mern-app

networks:
  mern-app:
    driver: bridge
volumes: 
  mysql-data:
    driver: local
