module.exports = [
    {
        "id": 1,
        "name": "Best Of You",
        "youtube_link": "https://youtu.be/h_L4Rixya64",
        "length": "04:15:00",
        "lyrics": "to be added",
        "album_id": 1,
        "artist_id": 1,
        "uploaded_at": "2009-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2008-12-31",
        "deleted_at": null,
    },
    {
        "id": 2,
        "name": "The Pretender",
        "youtube_link": "https://youtu.be/SBjQ9tuuTJQ",
        "length": "04:30:00",
        "lyrics": "Keep you in the dark You know they all pretend Keep you in the dark And so it all began Send in your skeletons Sing as their bones go marching in, again The need you buried deep The secrets that you keep are ever ready Are you ready? I'm finished making sense Done pleading ignorance That whole defense Spinning infinity, boy The wheel is spinning me It's never-ending, never-ending Same old story What if I say I'm not like the others? What if I say I'm not just another one of your plays? You're the pretender What if I say I will never surrender? What if I say I'm not like the others? What if I say I'm not just another one of your plays? You're the pretender What if I say that I'll never surrender? In time our soul untold I'm just another soul for sale, oh well The page is out of print We are not permanent We're temporary, temporary Same old story What if I say I'm not like the others? What if I say I'm not just another one of your plays? You're the pretender What if I say that I'll never surrender? What if I say I'm not like the others? What if I say I'm not just another one of your plays? You're the pretender What if I say that I'll never surrender? I'm the voice inside your head You refuse to hear I'm the face that you have to face Mirrored in your stare I'm what's left, I'm what's right I'm the enemy I'm the hand that will take you down Bring you to your knees So who are you? Yeah, who are you? Yeah, who are you? Yeah, who are you? Keep you in the dark You know they all pretend What if I say I'm not like the others? What if I say I'm not just another one of your plays? You're the pretender What if I say I will never surrender? What if I say I'm not like the others? What if I say I'm not just another one of your plays? You're the pretender What if I say that I'll never surrender? What if I say I'm not like the others? (Keep you in the dark) What if I say I'm not just another one of your plays? (You know they all pretend) You're the pretender (Who dares) What if I say I will never surrender? What if I say I'm not like the others? (Keep you in the dark) What if I say I'm not just another one of your plays? (You know they all pretend) You're the pretender (Who dares) What if I say I will never surrender? So who are you? Yeah, who are you? Yeah, who are you?",
        "album_id": 1,
        "artist_id": 1,
        "uploaded_at": "2009-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2008-12-31",
        "deleted_at": null,
    },
    {
        "id": 3,
        "name": "All My Life",
        "youtube_link": "https://youtu.be/xQ04WbgI9rg",
        "length": "04:44:00",
        "lyrics": "to be added",
        "album_id": 1,
        "artist_id": 1,
        "uploaded_at": "2009-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2008-12-31",
        "deleted_at": null,
    },
    {
        "id": 4,
        "name": "Everlong",
        "youtube_link": "https://youtu.be/eBG7P-K-r1Y",
        "length": "04:49:00",
        "lyrics": "to be added",
        "album_id": 1,
        "artist_id": 1,
        "uploaded_at": "2009-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2008-12-31",
        "deleted_at": null,
    },
    {
        "id": 5,
        "name": "Cant Stop",
        "youtube_link": "https://youtu.be/8DyziWtkfBw",
        "length": "04:37:00",
        "lyrics": "to be added",
        "album_id": 2,
        "artist_id": 2,
        "uploaded_at": "2002-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2001-12-31",
        "deleted_at": null,
    },
    {
        "id": 6,
        "name": "By The Way",
        "youtube_link": "https://youtu.be/JnfyjwChuNU",
        "length": "03:37:00",
        "lyrics": "to be added",
        "album_id": 2,
        "artist_id": 2,
        "uploaded_at": "2002-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2001-12-31",
        "deleted_at": null,
    },
    {
        "id": 7,
        "name": "This Is The Place",
        "youtube_link": "https://youtu.be/gqgm7ViA2Ag",
        "length": "04:17:00",
        "lyrics": "to be added",
        "album_id": 2,
        "artist_id": 2,
        "uploaded_at": "2002-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2001-12-31",
        "deleted_at": null,
    },
    {
        "id": 8,
        "name": "Never Mine",
        "youtube_link": "https://youtu.be/zk3bQ3CJNg4",
        "length": "03:45:00",
        "lyrics": "to be added",
        "album_id": 3,
        "artist_id": 3,
        "uploaded_at": "2020-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2019-12-31",
        "deleted_at": null,
    },
    {
        "id": 9,
        "name": "Coffee Stains",
        "youtube_link": "https://youtu.be/5kDr5863BoI",
        "length": "03:14:00",
        "lyrics": "to be added",
        "album_id": 3,
        "artist_id": 3,
        "uploaded_at": "2020-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2019-12-31",
        "deleted_at": null,
    },
    {
        "id": 10,
        "name": "Oh Sister",
        "youtube_link": "https://youtu.be/YSg9qE-oDGU",
        "length": "03:30:00",
        "lyrics": "to be added",
        "album_id": 3,
        "artist_id": 3,
        "uploaded_at": "2020-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2019-12-31",
        "deleted_at": null,
    },
    {
        "id": 11,
        "name": "Misguided Ghosts",
        "youtube_link": "https://youtu.be/oGWeHPK3NC4",
        "length": "02:58:00",
        "lyrics": "to be added",
        "album_id": 4,
        "artist_id": 4,
        "uploaded_at": "2009-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2008-12-31",
        "deleted_at": null,
    },
    {
        "id": 12,
        "name": "All I Wanted",
        "youtube_link": "https://youtu.be/W7nmB20qJv4",
        "length": "03:45:00",
        "lyrics": "to be added",
        "album_id": 4,
        "artist_id": 4,
        "uploaded_at": "2009-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2008-12-31",
        "deleted_at": null,
    },
    {
        "id": 13,
        "name": "Where The Lines Overlap",
        "youtube_link": "https://youtu.be/blDjUkMA9oU",
        "length": "03:16:00",
        "lyrics": "to be added",
        "album_id": 4,
        "artist_id": 4,
        "uploaded_at": "2009-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2008-12-31",
        "deleted_at": null,
    },
    {
        "id": 14,
        "name": "myboy",
        "youtube_link": "https://youtu.be/dVUmSgzgOqs",
        "length": "02:50:00",
        "lyrics": "to be added",
        "album_id": 5,
        "artist_id": 5,
        "uploaded_at": "2017-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2016-12-31",
        "deleted_at": null,
    },
    {
        "id": 15,
        "name": "party favor",
        "youtube_link": "https://youtu.be/tGHTOVw6F4Q",
        "length": "03:23:00",
        "lyrics": "to be added",
        "album_id": 5,
        "artist_id": 5,
        "uploaded_at": "2017-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2016-12-31",
        "deleted_at": null,
    },
    {
        "id": 16,
        "name": "idontwannabeyouanymore",
        "youtube_link": "https://youtu.be/-tn2S3kJlyU",
        "length": "03:24:00",
        "lyrics": "to be added",
        "album_id": 5,
        "artist_id": 5,
        "uploaded_at": "2017-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2016-12-31",
        "deleted_at": null,
    },
    {
        "id": 17,
        "name": "Come As You Are",
        "youtube_link": "https://youtu.be/vabnZ9-ex7o",
        "length": "03:45:00",
        "lyrics": "to be added",
        "album_id": 6,
        "artist_id": 6,
        "uploaded_at": "1991-02-02",
        "updated_at": "2020-09-24",
        "created_at": "1990-01-31",
        "deleted_at": null,
    },
    {
        "id": 18,
        "name": "Smells Like Teen Spirit",
        "youtube_link": "https://youtu.be/hTWKbfoikeg",
        "length": "04:38:00",
        "lyrics": "to be added",
        "album_id": 6,
        "artist_id": 6,
        "uploaded_at": "1991-02-02",
        "updated_at": "2020-09-24",
        "created_at": "1990-01-31",
        "deleted_at": null,
    },
    {
        "id": 19,
        "name": "Lithium",
        "youtube_link": "https://youtu.be/LYfnBsaTVEo",
        "length": "04:17:00",
        "lyrics": "to be added",
        "album_id": 6,
        "artist_id": 6,
        "uploaded_at": "1991-02-02",
        "updated_at": "2020-09-24",
        "created_at": "1990-01-31",
        "deleted_at": null,
    },
    {
        "id": 20,
        "name": "Tribute",
        "youtube_link": "https://youtu.be/_lK4cX5xGiQ",
        "length": "04:52:00",
        "lyrics": "to be added",
        "album_id": 7,
        "artist_id": 7,
        "uploaded_at": "2001-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2001-01-01",
        "deleted_at": null,
    },
    {
        "id": 21,
        "name": "Wonderboy",
        "youtube_link": "https://youtu.be/FL4HSiGvk68",
        "length": "04:31:00",
        "lyrics": "to be added",
        "album_id": 7,
        "artist_id": 7,
        "uploaded_at": "2001-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2001-01-01",
        "deleted_at": null,
    },
    {
        "id": 22,
        "name": "Kielbasa",
        "youtube_link": "https://youtu.be/7LBxr5ZScqE",
        "length": "03:00:00",
        "lyrics": "to be added",
        "album_id": 7,
        "artist_id": 7,
        "uploaded_at": "2001-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2001-01-01",
        "deleted_at": null,
    },
    {
        "id": 23,
        "name": "Dear God",
        "youtube_link": "https://youtu.be/mzX0rhF8buo",
        "length": "04:42:00",
        "lyrics": "to be added",
        "album_id": 8,
        "artist_id": 8,
        "uploaded_at": "2007-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2007-01-01",
        "deleted_at": null,
    },
    {
        "id": 24,
        "name": "So Far Away",
        "youtube_link": "https://youtu.be/A7ry4cx6HfY",
        "length": "05:28:00",
        "lyrics": "to be added",
        "album_id": 11,
        "artist_id": 8,
        "uploaded_at": "2010-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2010-01-01",
        "deleted_at": null,
    },
    {
        "id": 25,
        "name": "Buried Alive",
        "youtube_link": "https://youtu.be/imwmmv9r1oE",
        "length": "06:47:00",
        "lyrics": "to be added",
        "album_id": 11,
        "artist_id": 8,
        "uploaded_at": "2010-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2010-01-01",
        "deleted_at": null,
    },
    {
        "id": 26,
        "name": "Gunslinger",
        "youtube_link": "https://youtu.be/3vDetD8cW_o",
        "length": "04:11:00",
        "lyrics": "to be added",
        "album_id": 8,
        "artist_id": 8,
        "uploaded_at": "2007-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2007-01-01",
        "deleted_at": null,
    },
    {
        "id": 27,
        "name": "Space Bound",
        "youtube_link": "https://youtu.be/JByDbPn6A1o",
        "length": "04:24:00",
        "lyrics": "to be added",
        "album_id": 9,
        "artist_id": 9,
        "uploaded_at": "2010-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2010-01-01",
        "deleted_at": null,
    },
    {
        "id": 28,
        "name": "Love The Way You Lie",
        "youtube_link": "https://youtu.be/uelHwf8o7_U",
        "length": "04:26:00",
        "lyrics": "to be added",
        "album_id": 9,
        "artist_id": 9,
        "uploaded_at": "2010-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2010-01-01",
        "deleted_at": null,
    },
    {
        "id": 29,
        "name": "Not Afraid",
        "youtube_link": "https://youtu.be/j5-yKhDd64s",
        "length": "04:18:00",
        "lyrics": "to be added",
        "album_id": 9,
        "artist_id": 9,
        "uploaded_at": "2010-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2010-01-01",
        "deleted_at": null,
    },
    {
        "id": 30,
        "name": "Evil Angel",
        "youtube_link": "https://youtu.be/Wjrh8vid0IE",
        "length": "03:40:00",
        "lyrics": "to be added",
        "album_id": 10,
        "artist_id": 10,
        "uploaded_at": "2009-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2009-01-01",
        "deleted_at": null,
    },
    {
        "id": 31,
        "name": "Unknown Soldier",
        "youtube_link": "https://youtu.be/SQl3waLGR4s",
        "length": "03:42:00",
        "lyrics": "to be added",
        "album_id": 10,
        "artist_id": 10,
        "uploaded_at": "2009-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2009-01-01",
        "deleted_at": null,
    },
    {
        "id": 32,
        "name": "The Diary Of Jane",
        "youtube_link": "https://youtu.be/DWaB4PXCwFU",
        "length": "03:27:00",
        "lyrics": "to be added",
        "album_id": 10,
        "artist_id": 10,
        "uploaded_at": "2009-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2009-01-01",
        "deleted_at": null,
    },
    {
        "id": 33,
        "name": "Breath",
        "youtube_link": "https://youtu.be/Ib9swdvt3mA",
        "length": "03:38:00",
        "lyrics": "to be added",
        "album_id": 10,
        "artist_id": 10,
        "uploaded_at": "2009-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2009-01-01",
        "deleted_at": null,
    },
    {
        "id": 68,
        "name": "Muddy Waters",
        "youtube_link": "https://youtu.be/o6SprGmHTy4",
        "length": "04:30:00",
        "lyrics": "tobeadded",
        "album_id": 16,
        "artist_id": 11,
        "uploaded_at": "2016-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2016-02-01",
        "deleted_at": null,
    },
    {
        "id": 69,
        "name": "No Witness",
        "youtube_link": "https://youtu.be/-v9Pobv7y8Y",
        "length": "03:55:00",
        "lyrics": "tobeadded",
        "album_id": 16,
        "artist_id": 11,
        "uploaded_at": "2016-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2016-02-01",
        "deleted_at": null,
    },
    {
        "id": 70,
        "name": "Lost on You",
        "youtube_link": "https://youtu.be/wDjeBNv6ip0",
        "length": "05:08:00",
        "lyrics": "tobeadded",
        "album_id": 16,
        "artist_id": 11,
        "uploaded_at": "2016-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2016-02-01",
        "deleted_at": null,
    },
    {
        "id": 71,
        "name": "Sorry, Blame It On Me",
        "youtube_link": "https://youtu.be/ynMk2EwRi4Q",
        "length": "04:55:00",
        "lyrics": "tobeadded",
        "album_id": 17,
        "artist_id": 12,
        "uploaded_at": "2006-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2006-02-01",
        "deleted_at": null,
    },
    {
        "id": 72,
        "name": "Never Took The Time",
        "youtube_link": "https://youtu.be/tYCmv4aJtpU",
        "length": "03:57:00",
        "lyrics": "tobeadded",
        "album_id": 17,
        "artist_id": 12,
        "uploaded_at": "2006-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2006-02-01",
        "deleted_at": null,
    },
    {
        "id": 73,
        "name": "Smack That ",
        "youtube_link": "https://youtu.be/RsrR0l76i_4",
        "length": "03:32:00",
        "lyrics": "tobeadded",
        "album_id": 17,
        "artist_id": 12,
        "uploaded_at": "2006-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2006-02-01",
        "deleted_at": null,
    },
    {
        "id": 74,
        "name": "Help Is On The Way",
        "youtube_link": "https://youtu.be/JHiqGqoIGII",
        "length": "04:18:00",
        "lyrics": "tobeadded",
        "album_id": 18,
        "artist_id": 13,
        "uploaded_at": "2011-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2011-02-01",
        "deleted_at": null,
    },
    {
        "id": 75,
        "name": "Satellite",
        "youtube_link": "https://youtu.be/6nQCxwneUwA",
        "length": "03:58:00",
        "lyrics": "tobeadded",
        "album_id": 18,
        "artist_id": 13,
        "uploaded_at": "2011-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2011-02-01",
        "deleted_at": null,
    },
    {
        "id": 76,
        "name": "Hero Of War",
        "youtube_link": "https://youtu.be/_DboMAghWcA",
        "length": "04:16:00",
        "lyrics": "tobeadded",
        "album_id": 19,
        "artist_id": 13,
        "uploaded_at": "2008-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2008-02-01",
        "deleted_at": null,
    },
    {
        "id": 77,
        "name": "Savior",
        "youtube_link": "https://youtu.be/e8X3ACToii0",
        "length": "04:03:00",
        "lyrics": "tobeadded",
        "album_id": 19,
        "artist_id": 13,
        "uploaded_at": "2008-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2008-02-01",
        "deleted_at": null,
    },
    {
        "id": 78,
        "name": "Audience Of One",
        "youtube_link": "https://youtu.be/4MjLKjPc7q8",
        "length": "04:08:00",
        "lyrics": "tobeadded",
        "album_id": 19,
        "artist_id": 13,
        "uploaded_at": "2008-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2008-02-01",
        "deleted_at": null,
    },
    {
        "id": 79,
        "name": "Skeletons",
        "youtube_link": "https://youtu.be/h0_h7vUcnhs",
        "length": "03:55:00",
        "lyrics": "tobeadded",
        "album_id": 20,
        "artist_id": 14,
        "uploaded_at": "2015-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2015-02-01",
        "deleted_at": null,
    },
    {
        "id": 80,
        "name": "Falling Apart",
        "youtube_link": "https://youtu.be/aqYnMSUTFGU",
        "length": "03:20:00",
        "lyrics": "tobeadded",
        "album_id": 20,
        "artist_id": 14,
        "uploaded_at": "2015-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2015-02-01",
        "deleted_at": null,
    },
    {
        "id": 81,
        "name": "Face Everything And Rise",
        "youtube_link": "https://youtu.be/g9z4DWB7Iy8",
        "length": "03:18:00",
        "lyrics": "tobeadded",
        "album_id": 20,
        "artist_id": 14,
        "uploaded_at": "2015-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2015-02-01",
        "deleted_at": null,
    },
    {
        "id": 82,
        "name": "You",
        "youtube_link": "https://youtu.be/OzL7u5teZhg",
        "length": "03:28:00",
        "lyrics": "tobeadded",
        "album_id": 21,
        "artist_id": 15,
        "uploaded_at": "1993-02-01",
        "updated_at": "2020-09-24",
        "created_at": "1993-02-01",
        "deleted_at": null,
    },
    {
        "id": 83,
        "name": "Thinking About You",
        "youtube_link": "https://youtu.be/2jsPEOiMNaA",
        "length": "02:41:00",
        "lyrics": "tobeadded",
        "album_id": 21,
        "artist_id": 15,
        "uploaded_at": "1993-02-01",
        "updated_at": "2020-09-24",
        "created_at": "1993-02-01",
        "deleted_at": null,
    },
    {
        "id": 84,
        "name": "Creep",
        "youtube_link": "https://youtu.be/zFYEYRcjK2g",
        "length": "03:58:00",
        "lyrics": "tobeadded",
        "album_id": 21,
        "artist_id": 15,
        "uploaded_at": "1993-02-01",
        "updated_at": "2020-09-24",
        "created_at": "1993-02-01",
        "deleted_at": null,
    },
    {
        "id": 85,
        "name": "Northern Downpour",
        "youtube_link": "https://youtu.be/zouSojyIi94",
        "length": "04:10:00",
        "lyrics": "tobeadded",
        "album_id": 22,
        "artist_id": 16,
        "uploaded_at": "2008-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2008-02-01",
        "deleted_at": null,
    },
    {
        "id": 86,
        "name": "Nine In The Afternoon",
        "youtube_link": "https://youtu.be/yCto3PCn8wo",
        "length": "03:17:00",
        "lyrics": "tobeadded",
        "album_id": 22,
        "artist_id": 16,
        "uploaded_at": "2008-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2008-02-01",
        "deleted_at": null,
    },
    {
        "id": 87,
        "name": "When the Day Met the Night",
        "youtube_link": "https://youtu.be/W4Jaqb4sA1E",
        "length": "04:53:00",
        "lyrics": "tobeadded",
        "album_id": 22,
        "artist_id": 16,
        "uploaded_at": "2008-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2008-02-01",
        "deleted_at": null,
    },
    {
        "id": 88,
        "name": "This Is Gospel",
        "youtube_link": "https://youtu.be/tGE381tbQa8",
        "length": "03:10:00",
        "lyrics": "tobeadded",
        "album_id": 23,
        "artist_id": 16,
        "uploaded_at": "2013-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2013-02-01",
        "deleted_at": null,
    },
    {
        "id": 89,
        "name": "Nicotine",
        "youtube_link": "https://youtu.be/LkBxcmxWKAA",
        "length": "03:16:00",
        "lyrics": "tobeadded",
        "album_id": 23,
        "artist_id": 16,
        "uploaded_at": "2013-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2013-02-01",
        "deleted_at": null,
    },
    {
        "id": 90,
        "name": "Casual Affair",
        "youtube_link": "https://youtu.be/zyx0W5UhJGM",
        "length": "03:31:00",
        "lyrics": "tobeadded",
        "album_id": 23,
        "artist_id": 16,
        "uploaded_at": "2013-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2013-02-01",
        "deleted_at": null,
    },
    {
        "id": 91,
        "name": "Victorious",
        "youtube_link": "https://youtu.be/AUChk0lxF44",
        "length": "02:59:00",
        "lyrics": "tobeadded",
        "album_id": 24,
        "artist_id": 16,
        "uploaded_at": "2016-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2016-02-01",
        "deleted_at": null,
    },
    {
        "id": 92,
        "name": "Don't Threaten Me With A Good Time",
        "youtube_link": "https://youtu.be/H5NqIsnyTG8",
        "length": "03:44:00",
        "lyrics": "tobeadded",
        "album_id": 24,
        "artist_id": 16,
        "uploaded_at": "2016-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2016-02-01",
        "deleted_at": null,
    },
    {
        "id": 93,
        "name": "Death Of A Bachelor",
        "youtube_link": "https://youtu.be/R03cqGg40GU",
        "length": "03:32:00",
        "lyrics": "tobeadded",
        "album_id": 24,
        "artist_id": 16,
        "uploaded_at": "2016-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2016-02-01",
        "deleted_at": null,
    },
    {
        "id": 94,
        "name": "Emperor's New Clothes",
        "youtube_link": "https://youtu.be/7qFF2v8VsaA",
        "length": "03:39:00",
        "lyrics": "tobeadded",
        "album_id": 24,
        "artist_id": 16,
        "uploaded_at": "2016-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2016-02-01",
        "deleted_at": null,
    },
    {
        "id": 95,
        "name": "Take Me To Church",
        "youtube_link": "https://youtu.be/PVjiKRfKpPI",
        "length": "04:16:00",
        "lyrics": "tobeadded",
        "album_id": 25,
        "artist_id": 17,
        "uploaded_at": "2014-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2014-02-01",
        "deleted_at": null,
    },
    {
        "id": 96,
        "name": "Someone New",
        "youtube_link": "https://youtu.be/bPJSsAr2iu0",
        "length": "04:02:00",
        "lyrics": "tobeadded",
        "album_id": 25,
        "artist_id": 17,
        "uploaded_at": "2014-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2014-02-01",
        "deleted_at": null,
    },
    {
        "id": 97,
        "name": "Never Going Back Again",
        "youtube_link": "https://youtu.be/qTesFEPmLI4",
        "length": "02:14:00",
        "lyrics": "tobeadded",
        "album_id": 26,
        "artist_id": 18,
        "uploaded_at": "1977-02-01",
        "updated_at": "2020-09-24",
        "created_at": "1999-02-01",
        "deleted_at": null,
    },
    {
        "id": 98,
        "name": "Second Hand News",
        "youtube_link": "https://youtu.be/bLfcwDZ5GzQ",
        "length": "02:56:00",
        "lyrics": "tobeadded",
        "album_id": 26,
        "artist_id": 18,
        "uploaded_at": "1977-02-01",
        "updated_at": "2020-09-24",
        "created_at": "1999-02-01",
        "deleted_at": null,
    },
    {
        "id": 99,
        "name": "Go Your Own Way",
        "youtube_link": "https://youtu.be/DubafeFeJ7Y",
        "length": "03:43:00",
        "lyrics": "tobeadded",
        "album_id": 26,
        "artist_id": 18,
        "uploaded_at": "1977-02-01",
        "updated_at": "2020-09-24",
        "created_at": "1999-02-01",
        "deleted_at": null,
    },
    {
        "id": 100,
        "name": "The Chain",
        "youtube_link": "https://youtu.be/iLC-tHvkNvI",
        "length": "04:30:00",
        "lyrics": "tobeadded",
        "album_id": 26,
        "artist_id": 18,
        "uploaded_at": "1977-02-01",
        "updated_at": "2020-09-24",
        "created_at": "1999-02-01",
        "deleted_at": null,
    },
    {
        "id": 101,
        "name": "Better Together",
        "youtube_link": "https://youtu.be/fqxNYjDFJUk",
        "length": "03:27:00",
        "lyrics": "tobeadded",
        "album_id": 27,
        "artist_id": 19,
        "uploaded_at": "2005-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2005-02-01",
        "deleted_at": null,
    },
    {
        "id": 102,
        "name": "Banana Pancakes",
        "youtube_link": "https://youtu.be/OkyrIRyrRdY",
        "length": "04:40:00",
        "lyrics": "tobeadded",
        "album_id": 27,
        "artist_id": 19,
        "uploaded_at": "2005-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2005-02-01",
        "deleted_at": null,
    },
    {
        "id": 103,
        "name": "Do You Remember",
        "youtube_link": "https://youtu.be/9HEGXRqaod8",
        "length": "02:24:00",
        "lyrics": "tobeadded",
        "album_id": 27,
        "artist_id": 19,
        "uploaded_at": "2005-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2005-02-01",
        "deleted_at": null,
    },
    {
        "id": 104,
        "name": "Sitting, Waiting, Wishing",
        "youtube_link": "https://youtu.be/IhTvifGShw4",
        "length": "04:54:00",
        "lyrics": "tobeadded",
        "album_id": 27,
        "artist_id": 19,
        "uploaded_at": "2005-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2005-02-01",
        "deleted_at": null,
    },
    {
        "id": 105,
        "name": "Space Oddity",
        "youtube_link": "https://youtu.be/iYYRH4apXDo",
        "length": "05:04:00",
        "lyrics": "tobeadded",
        "album_id": 28,
        "artist_id": 20,
        "uploaded_at": "2016-02-01",
        "updated_at": "2020-09-24",
        "created_at": "1976-01-01",
        "deleted_at": null,
    },
    {
        "id": 106,
        "name": "Changes",
        "youtube_link": "https://youtu.be/BPPSu0vaNWA",
        "length": "03:37:00",
        "lyrics": "tobeadded",
        "album_id": 28,
        "artist_id": 20,
        "uploaded_at": "2016-02-01",
        "updated_at": "2020-09-24",
        "created_at": "1976-01-01",
        "deleted_at": null,
    },
    {
        "id": 107,
        "name": "Ziggy Stardust",
        "youtube_link": "https://youtu.be/D8R_u3Yfwcs",
        "length": "03:13:00",
        "lyrics": "tobeadded",
        "album_id": 28,
        "artist_id": 20,
        "uploaded_at": "2016-02-01",
        "updated_at": "2020-09-24",
        "created_at": "1976-01-01",
        "deleted_at": null,
    },
    {
        "id": 108,
        "name": "Bow Down",
        "youtube_link": "https://youtu.be/VDZEpxheh6E",
        "length": "04:02:00",
        "lyrics": "tobeadded",
        "album_id": 29,
        "artist_id": 21,
        "uploaded_at": "2019-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2019-01-01",
        "deleted_at": null,
    },
    {
        "id": 109,
        "name": "Every Time You Leave",
        "youtube_link": "https://youtu.be/7cpKoLkkg28",
        "length": "03:36:00",
        "lyrics": "tobeadded",
        "album_id": 29,
        "artist_id": 21,
        "uploaded_at": "2019-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2019-01-01",
        "deleted_at": null,
    },
    {
        "id": 110,
        "name": "Hurricane",
        "youtube_link": "https://youtu.be/-7p1LhXqMnc",
        "length": "03:43:00",
        "lyrics": "tobeadded",
        "album_id": 29,
        "artist_id": 21,
        "uploaded_at": "2019-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2019-01-01",
        "deleted_at": null,
    },
    {
        "id": 111,
        "name": "Hotel California",
        "youtube_link": "https://youtu.be/811QZGDysx0",
        "length": "06:31:00",
        "lyrics": "tobeadded",
        "album_id": 30,
        "artist_id": 22,
        "uploaded_at": "2013-02-01",
        "updated_at": "2020-09-24",
        "created_at": "1976-01-01",
        "deleted_at": null,
    },
    {
        "id": 112,
        "name": "The Last Resort",
        "youtube_link": "https://youtu.be/LeRg8LUwP4g",
        "length": "07:24:00",
        "lyrics": "tobeadded",
        "album_id": 30,
        "artist_id": 22,
        "uploaded_at": "2013-02-01",
        "updated_at": "2020-09-24",
        "created_at": "1976-01-01",
        "deleted_at": null,
    },
    {
        "id": 113,
        "name": "Light Me Up",
        "youtube_link": "https://youtu.be/8X5NLBLOBfU",
        "length": "03:27:00",
        "lyrics": "tobeadded",
        "album_id": 31,
        "artist_id": 23,
        "uploaded_at": "2010-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2010-02-01",
        "deleted_at": null,
    },
    {
        "id": 114,
        "name": "Make Me Wanna Die",
        "youtube_link": "https://youtu.be/txBfhpm1jI0",
        "length": "03:58:00",
        "lyrics": "tobeadded",
        "album_id": 31,
        "artist_id": 23,
        "uploaded_at": "2010-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2010-02-01",
        "deleted_at": null,
    },
    {
        "id": 115,
        "name": "All the Right Moves",
        "youtube_link": "https://youtu.be/RuPm04f9BUk",
        "length": "03:56:00",
        "lyrics": "tobeadded",
        "album_id": 32,
        "artist_id": 24,
        "uploaded_at": "2009-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2009-01-01",
        "deleted_at": null,
    },
    {
        "id": 116,
        "name": "Good Life",
        "youtube_link": "https://youtu.be/XB2uE0KuedI",
        "length": "04:13:00",
        "lyrics": "tobeadded",
        "album_id": 32,
        "artist_id": 24,
        "uploaded_at": "2009-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2009-01-01",
        "deleted_at": null,
    },
    {
        "id": 117,
        "name": "Secrets",
        "youtube_link": "https://youtu.be/NhyRD2xunL0",
        "length": "03:45:00",
        "lyrics": "tobeadded",
        "album_id": 32,
        "artist_id": 24,
        "uploaded_at": "2009-02-01",
        "updated_at": "2020-09-24",
        "created_at": "2009-01-01",
        "deleted_at": null,
    }
]