name: Check Tests

on:
  push:
    branches:
    - test-workflow # specify the branch you want the deploy to take place from

env:
  DB_PASS: ${{ secrets.DB_PASS }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_NAME: ${{ secrets.DB_NAME }}
  ENV_FILE: ${{ secrets.ENV_FILE }} # Secret with all additional environment variables.
  SERVER_PORT: 8080 # the port your server is running on
  CMDTORUN: npm run spinseedup
  TEST_CONTAINER: test-container
  # docker exec song-app_test-container_1 npm run test

jobs:   
  server-tests:
      # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: database_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    # strategy:
    #   matrix:
    #     node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      # - name: Setup node  (Node.js ${{ matrix.node-version }})
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: ${{ matrix.node-version }}
      - name: Install Server dependencies
        run: npm ci
        working-directory: ./server
      - name: migrate database and test
        run: npm run spintest
        env:
          MYSQL_DATABASE_TEST: database_test
          MYSQL_PASSWORD: null
        working-directory: ./server
