name: Build and Deploy to Google Compute Engine

on:
  push:
    branches:
    - specifyabranch

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  GCP_ID: ${{ secrets.RUN_PROJECT }}
  GCE_INSTANCE: docker-instance-1  # TODO: update to instance name
  GCE_INSTANCE_ZONE: us-central1-a   # TODO: update to instance zone
  SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
  PWD: ${{ secrets.PWD }}
  USER: ${{ secrets.USER }}
  GCE_HOST: ${{ secrets.DB_HOST }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        project_id: ${{ secrets.RUN_PROJECT }}    
    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker
    - name: Install dependencies
      run: npm ci
      working-directory: ./songclient
    # Build production build 
    - name: Build songclient
      run: CI=false npm run build
      working-directory: ./songclient
     #Build the Docker image
    - name: Build
      run: |-
        docker build --tag "gcr.io/$PROJECT_ID/$GCE_INSTANCE-image:$GITHUB_SHA" .
    # Push the Docker image to Google Container Registry
    - name: Publish Image
      run: |-
        docker push "gcr.io/$PROJECT_ID/$GCE_INSTANCE-image:$GITHUB_SHA"
    - name: Create Instance with Container
      run: |-
        gcloud compute instances create-with-container "$GCE_INSTANCE" \
        --container-image "gcr.io/$PROJECT_ID/$GCE_INSTANCE-image:$GITHUB_SHA" \
        --image-project cos-cloud \
        --image cos-stable-85-13310-1041-28 \
        --zone "$GCE_INSTANCE_ZONE" \
        --service-account "$SERVICE_ACCOUNT" \
        --tags http-server \
        --machine-type e2-medium
    - name: Deploy to containerized instance
      run: |-
        gcloud compute instances update-container "$GCE_INSTANCE" \
          --zone "$GCE_INSTANCE_ZONE" \
          --container-image "gcr.io/$PROJECT_ID/$GCE_INSTANCE-image:$GITHUB_SHA" \
          --container-env=[DB_HOST=$GCE_HOST,DB_PASSWORD=${{secrets.PWD}}]